# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MQTT_msg.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='MQTT_msg.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0eMQTT_msg.proto\"J\n\x0b\x42otPosition\x12\x0e\n\x06\x62ot_id\x18\x01 \x01(\x05\x12\r\n\x05x_cod\x18\x02 \x01(\x02\x12\r\n\x05y_cod\x18\x03 \x01(\x02\x12\r\n\x05\x61ngle\x18\x04 \x01(\x02\"1\n\x0e\x42otPositionArr\x12\x1f\n\tpositions\x18\x01 \x03(\x0b\x32\x0c.BotPositionb\x06proto3')
)




_BOTPOSITION = _descriptor.Descriptor(
  name='BotPosition',
  full_name='BotPosition',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='bot_id', full_name='BotPosition.bot_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='x_cod', full_name='BotPosition.x_cod', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y_cod', full_name='BotPosition.y_cod', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='angle', full_name='BotPosition.angle', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=92,
)


_BOTPOSITIONARR = _descriptor.Descriptor(
  name='BotPositionArr',
  full_name='BotPositionArr',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='positions', full_name='BotPositionArr.positions', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=94,
  serialized_end=143,
)

_BOTPOSITIONARR.fields_by_name['positions'].message_type = _BOTPOSITION
DESCRIPTOR.message_types_by_name['BotPosition'] = _BOTPOSITION
DESCRIPTOR.message_types_by_name['BotPositionArr'] = _BOTPOSITIONARR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BotPosition = _reflection.GeneratedProtocolMessageType('BotPosition', (_message.Message,), dict(
  DESCRIPTOR = _BOTPOSITION,
  __module__ = 'MQTT_msg_pb2'
  # @@protoc_insertion_point(class_scope:BotPosition)
  ))
_sym_db.RegisterMessage(BotPosition)

BotPositionArr = _reflection.GeneratedProtocolMessageType('BotPositionArr', (_message.Message,), dict(
  DESCRIPTOR = _BOTPOSITIONARR,
  __module__ = 'MQTT_msg_pb2'
  # @@protoc_insertion_point(class_scope:BotPositionArr)
  ))
_sym_db.RegisterMessage(BotPositionArr)


# @@protoc_insertion_point(module_scope)
