# Generated by Django 3.1.2 on 2021-02-01 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0003_botserver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='server_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='schedules.botserver'),
        ),
    ]
