# Generated by Django 3.1.2 on 2021-02-01 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0004_auto_20210201_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='botserver',
            name='enc_key',
            field=models.TextField(default='TEST'),
        ),
    ]
