# Generated by Django 3.1.2 on 2021-02-02 14:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedules', '0006_authorizeclients'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AuthorizeClients',
            new_name='AuthorizeClient',
        ),
    ]
